name: build-mingw
on: push
jobs:
  main:
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: compiler
      shell: cmd
      run: |
        if exist C:\mingw64 move /y C:\mingw64 C:\mingw64_
        call pull-mingw
    - name: source
      shell: cmd
      run: |
        set PATH=C:\Program Files\7-Zip;%PATH%
        if not exist llvmorg-19.1.7.zip (
            echo downloading llvmorg-19.1.7.zip
            curl -L -o llvmorg-19.1.7.zip https://github.com/llvm/llvm-project/archive/refs/tags/llvmorg-19.1.7.zip
        )
        7z rn llvmorg-19.1.7.zip llvm-project-llvmorg-19.1.7 llvm-project
        if not exist llvm-project 7z x -y llvmorg-19.1.7.zip
    - name: build
      shell: cmd
      run: |
        set PATH=C:\Program Files\7-Zip;C:\Program Files\CMake\bin;C:\mingw1310_64\bin;%PATH%
        pushd llvm-project
            if not exist build mkdir build
            pushd build
                cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_RTTI=on -DLLVM_ENABLE_EH=on -DLLVM_ENABLE_PROJECTS=clang -DCMAKE_INSTALL_PREFIX=C:\llvm19 ..\llvm
                ninja
            popd
        popd
    - name: install
      shell: cmd
      run: |
        set PATH=C:\Program Files\7-Zip;C:\Program Files\CMake\bin;C:\mingw1310_64\bin;%PATH%
        pushd llvm-project\build
            ninja install
        popd
        7z a -y llvm19-mingw.7z C:\llvm19
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: llvm19
        path: C:\llvm19
    - name: release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: llvm19-mingw.7z
