name: main
on: push
jobs:
  main:
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: clone
      shell: cmd
      run: |
        set PATH=C:\Program Files\Git\cmd;%PATH%
        if not exist llvm-project git clone https://github.com/llvm/llvm-project.git
    - name: build
      shell: cmd
      run: |
        set PATH=C:\Miniconda;C:\Miniconda\Scripts;C:\mingw1310_64\bin;C:\Windows;C:\Windows\System32
        move /y C:\mingw C:\mingw_
        call pull-mingw
        where ninja > NUL 2>&1 || pip install ninja
        where ninja > NUL 2>&1 || pip install ninja
        pushd llvm-project
            if not exist build mkdir build
            pushd build
                cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_RTTI=on -DLLVM_ENABLE_EH=on -DLLVM_ENABLE_PROJECTS=clang -DCMAKE_INSTALL_PREFIX=C:\llvm19 ..\llvm
                ninja
            popd
        popd
    - name: install
      shell: cmd
      run: |
        set PATH=C:\Miniconda;C:\Miniconda\Scripts;C:\mingw1310_64\bin;C:\Windows;C:\Windows\System32
        where ninja > NUL 2>&1 || pip install ninja
        pushd llvm-project\build
            ninja install
        popd
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: llvm19
        path: C:\llvm19
